public class FirstClass {
    public void fun2()
    {
system.debug('this is non static statement');
    }
    public static void fun1()
    {
 //datatype var = val
integer a=10;
system.debug(a);

String b='hari';
System.debug(b);

Boolean c=true;
System.debug(c);

Date dt=System.today();
System.debug(dt);

id recordid='a00dL000002E3WOQA0';
system.debug(recordid);

decimal dc=9.33423;
system.debug(dc);

system.debug('this is static statement');
    }
    
    
    
}